server:
  port: 9190
  servlet:
    context-path: /course-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database: mysql